// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: players.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Messages {

  /// <summary>Holder for reflection information generated from players.proto</summary>
  public static partial class PlayersReflection {

    #region Descriptor
    /// <summary>File descriptor for players.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PlayersReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1wbGF5ZXJzLnByb3RvEghtZXNzYWdlcxoOZW50aXRpZXMucHJvdG8iTQoP",
            "UGxheWVyQ29ubmVjdGVkEgoKAmlkGAEgASgFEi4KDWVudGl0eVNwYXduZWQY",
            "CCABKAsyFy5tZXNzYWdlcy5FbnRpdHlTcGF3bmVkQjAKIGNvbS5zbS5tbW8u",
            "bW9iYS5uZXR3b3JrLnByb3RvYnVmQgxQbGF5ZXJQcm90b3NiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Messages.EntitiesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Messages.PlayerConnected), global::Messages.PlayerConnected.Parser, new[]{ "Id", "EntitySpawned" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class PlayerConnected : pb::IMessage<PlayerConnected> {
    private static readonly pb::MessageParser<PlayerConnected> _parser = new pb::MessageParser<PlayerConnected>(() => new PlayerConnected());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PlayerConnected> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Messages.PlayersReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerConnected() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerConnected(PlayerConnected other) : this() {
      id_ = other.id_;
      entitySpawned_ = other.entitySpawned_ != null ? other.entitySpawned_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerConnected Clone() {
      return new PlayerConnected(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "entitySpawned" field.</summary>
    public const int EntitySpawnedFieldNumber = 8;
    private global::Messages.EntitySpawned entitySpawned_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Messages.EntitySpawned EntitySpawned {
      get { return entitySpawned_; }
      set {
        entitySpawned_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PlayerConnected);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PlayerConnected other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (!object.Equals(EntitySpawned, other.EntitySpawned)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (entitySpawned_ != null) hash ^= EntitySpawned.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (entitySpawned_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(EntitySpawned);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (entitySpawned_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EntitySpawned);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PlayerConnected other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.entitySpawned_ != null) {
        if (entitySpawned_ == null) {
          entitySpawned_ = new global::Messages.EntitySpawned();
        }
        EntitySpawned.MergeFrom(other.EntitySpawned);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 66: {
            if (entitySpawned_ == null) {
              entitySpawned_ = new global::Messages.EntitySpawned();
            }
            input.ReadMessage(entitySpawned_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
