// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: items.proto

package com.sm.mmo.moba.network.protobuf;

public final class ItemProtos {
  private ItemProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:messages.Item)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *unique id of the item (so the server/client knows what item the user is picking up for example)
     * </pre>
     *
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <pre>
     *shotgun, armor, boots, potion, etc
     * </pre>
     *
     * <code>int32 type = 2;</code>
     */
    int getType();

    /**
     * <code>repeated .messages.ItemAttribute attributes = 3;</code>
     */
    java.util.List<com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute> 
        getAttributesList();
    /**
     * <code>repeated .messages.ItemAttribute attributes = 3;</code>
     */
    com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute getAttributes(int index);
    /**
     * <code>repeated .messages.ItemAttribute attributes = 3;</code>
     */
    int getAttributesCount();
    /**
     * <code>repeated .messages.ItemAttribute attributes = 3;</code>
     */
    java.util.List<? extends com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttributeOrBuilder> 
        getAttributesOrBuilderList();
    /**
     * <code>repeated .messages.ItemAttribute attributes = 3;</code>
     */
    com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttributeOrBuilder getAttributesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code messages.Item}
   */
  public  static final class Item extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:messages.Item)
      ItemOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Item.newBuilder() to construct.
    private Item(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Item() {
      id_ = 0;
      type_ = 0;
      attributes_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Item(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 16: {

              type_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                attributes_ = new java.util.ArrayList<com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute>();
                mutable_bitField0_ |= 0x00000004;
              }
              attributes_.add(
                  input.readMessage(com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          attributes_ = java.util.Collections.unmodifiableList(attributes_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sm.mmo.moba.network.protobuf.ItemProtos.internal_static_messages_Item_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sm.mmo.moba.network.protobuf.ItemProtos.internal_static_messages_Item_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sm.mmo.moba.network.protobuf.ItemProtos.Item.class, com.sm.mmo.moba.network.protobuf.ItemProtos.Item.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <pre>
     *unique id of the item (so the server/client knows what item the user is picking up for example)
     * </pre>
     *
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <pre>
     *shotgun, armor, boots, potion, etc
     * </pre>
     *
     * <code>int32 type = 2;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int ATTRIBUTES_FIELD_NUMBER = 3;
    private java.util.List<com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute> attributes_;
    /**
     * <code>repeated .messages.ItemAttribute attributes = 3;</code>
     */
    public java.util.List<com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute> getAttributesList() {
      return attributes_;
    }
    /**
     * <code>repeated .messages.ItemAttribute attributes = 3;</code>
     */
    public java.util.List<? extends com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttributeOrBuilder> 
        getAttributesOrBuilderList() {
      return attributes_;
    }
    /**
     * <code>repeated .messages.ItemAttribute attributes = 3;</code>
     */
    public int getAttributesCount() {
      return attributes_.size();
    }
    /**
     * <code>repeated .messages.ItemAttribute attributes = 3;</code>
     */
    public com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute getAttributes(int index) {
      return attributes_.get(index);
    }
    /**
     * <code>repeated .messages.ItemAttribute attributes = 3;</code>
     */
    public com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttributeOrBuilder getAttributesOrBuilder(
        int index) {
      return attributes_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (type_ != 0) {
        output.writeInt32(2, type_);
      }
      for (int i = 0; i < attributes_.size(); i++) {
        output.writeMessage(3, attributes_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, type_);
      }
      for (int i = 0; i < attributes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, attributes_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sm.mmo.moba.network.protobuf.ItemProtos.Item)) {
        return super.equals(obj);
      }
      com.sm.mmo.moba.network.protobuf.ItemProtos.Item other = (com.sm.mmo.moba.network.protobuf.ItemProtos.Item) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && (getType()
          == other.getType());
      result = result && getAttributesList()
          .equals(other.getAttributesList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      if (getAttributesCount() > 0) {
        hash = (37 * hash) + ATTRIBUTES_FIELD_NUMBER;
        hash = (53 * hash) + getAttributesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sm.mmo.moba.network.protobuf.ItemProtos.Item parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sm.mmo.moba.network.protobuf.ItemProtos.Item parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sm.mmo.moba.network.protobuf.ItemProtos.Item parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sm.mmo.moba.network.protobuf.ItemProtos.Item parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sm.mmo.moba.network.protobuf.ItemProtos.Item parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sm.mmo.moba.network.protobuf.ItemProtos.Item parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sm.mmo.moba.network.protobuf.ItemProtos.Item parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sm.mmo.moba.network.protobuf.ItemProtos.Item parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sm.mmo.moba.network.protobuf.ItemProtos.Item parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sm.mmo.moba.network.protobuf.ItemProtos.Item parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sm.mmo.moba.network.protobuf.ItemProtos.Item parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sm.mmo.moba.network.protobuf.ItemProtos.Item parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sm.mmo.moba.network.protobuf.ItemProtos.Item prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code messages.Item}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:messages.Item)
        com.sm.mmo.moba.network.protobuf.ItemProtos.ItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sm.mmo.moba.network.protobuf.ItemProtos.internal_static_messages_Item_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sm.mmo.moba.network.protobuf.ItemProtos.internal_static_messages_Item_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sm.mmo.moba.network.protobuf.ItemProtos.Item.class, com.sm.mmo.moba.network.protobuf.ItemProtos.Item.Builder.class);
      }

      // Construct using com.sm.mmo.moba.network.protobuf.ItemProtos.Item.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAttributesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        type_ = 0;

        if (attributesBuilder_ == null) {
          attributes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          attributesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sm.mmo.moba.network.protobuf.ItemProtos.internal_static_messages_Item_descriptor;
      }

      @java.lang.Override
      public com.sm.mmo.moba.network.protobuf.ItemProtos.Item getDefaultInstanceForType() {
        return com.sm.mmo.moba.network.protobuf.ItemProtos.Item.getDefaultInstance();
      }

      @java.lang.Override
      public com.sm.mmo.moba.network.protobuf.ItemProtos.Item build() {
        com.sm.mmo.moba.network.protobuf.ItemProtos.Item result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sm.mmo.moba.network.protobuf.ItemProtos.Item buildPartial() {
        com.sm.mmo.moba.network.protobuf.ItemProtos.Item result = new com.sm.mmo.moba.network.protobuf.ItemProtos.Item(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.type_ = type_;
        if (attributesBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            attributes_ = java.util.Collections.unmodifiableList(attributes_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.attributes_ = attributes_;
        } else {
          result.attributes_ = attributesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sm.mmo.moba.network.protobuf.ItemProtos.Item) {
          return mergeFrom((com.sm.mmo.moba.network.protobuf.ItemProtos.Item)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sm.mmo.moba.network.protobuf.ItemProtos.Item other) {
        if (other == com.sm.mmo.moba.network.protobuf.ItemProtos.Item.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (attributesBuilder_ == null) {
          if (!other.attributes_.isEmpty()) {
            if (attributes_.isEmpty()) {
              attributes_ = other.attributes_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureAttributesIsMutable();
              attributes_.addAll(other.attributes_);
            }
            onChanged();
          }
        } else {
          if (!other.attributes_.isEmpty()) {
            if (attributesBuilder_.isEmpty()) {
              attributesBuilder_.dispose();
              attributesBuilder_ = null;
              attributes_ = other.attributes_;
              bitField0_ = (bitField0_ & ~0x00000004);
              attributesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAttributesFieldBuilder() : null;
            } else {
              attributesBuilder_.addAllMessages(other.attributes_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sm.mmo.moba.network.protobuf.ItemProtos.Item parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sm.mmo.moba.network.protobuf.ItemProtos.Item) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <pre>
       *unique id of the item (so the server/client knows what item the user is picking up for example)
       * </pre>
       *
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <pre>
       *unique id of the item (so the server/client knows what item the user is picking up for example)
       * </pre>
       *
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *unique id of the item (so the server/client knows what item the user is picking up for example)
       * </pre>
       *
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <pre>
       *shotgun, armor, boots, potion, etc
       * </pre>
       *
       * <code>int32 type = 2;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <pre>
       *shotgun, armor, boots, potion, etc
       * </pre>
       *
       * <code>int32 type = 2;</code>
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *shotgun, armor, boots, potion, etc
       * </pre>
       *
       * <code>int32 type = 2;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute> attributes_ =
        java.util.Collections.emptyList();
      private void ensureAttributesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          attributes_ = new java.util.ArrayList<com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute>(attributes_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute, com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute.Builder, com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttributeOrBuilder> attributesBuilder_;

      /**
       * <code>repeated .messages.ItemAttribute attributes = 3;</code>
       */
      public java.util.List<com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute> getAttributesList() {
        if (attributesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(attributes_);
        } else {
          return attributesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .messages.ItemAttribute attributes = 3;</code>
       */
      public int getAttributesCount() {
        if (attributesBuilder_ == null) {
          return attributes_.size();
        } else {
          return attributesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .messages.ItemAttribute attributes = 3;</code>
       */
      public com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute getAttributes(int index) {
        if (attributesBuilder_ == null) {
          return attributes_.get(index);
        } else {
          return attributesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .messages.ItemAttribute attributes = 3;</code>
       */
      public Builder setAttributes(
          int index, com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute value) {
        if (attributesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributesIsMutable();
          attributes_.set(index, value);
          onChanged();
        } else {
          attributesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .messages.ItemAttribute attributes = 3;</code>
       */
      public Builder setAttributes(
          int index, com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute.Builder builderForValue) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.set(index, builderForValue.build());
          onChanged();
        } else {
          attributesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .messages.ItemAttribute attributes = 3;</code>
       */
      public Builder addAttributes(com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute value) {
        if (attributesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributesIsMutable();
          attributes_.add(value);
          onChanged();
        } else {
          attributesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .messages.ItemAttribute attributes = 3;</code>
       */
      public Builder addAttributes(
          int index, com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute value) {
        if (attributesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributesIsMutable();
          attributes_.add(index, value);
          onChanged();
        } else {
          attributesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .messages.ItemAttribute attributes = 3;</code>
       */
      public Builder addAttributes(
          com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute.Builder builderForValue) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.add(builderForValue.build());
          onChanged();
        } else {
          attributesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .messages.ItemAttribute attributes = 3;</code>
       */
      public Builder addAttributes(
          int index, com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute.Builder builderForValue) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.add(index, builderForValue.build());
          onChanged();
        } else {
          attributesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .messages.ItemAttribute attributes = 3;</code>
       */
      public Builder addAllAttributes(
          java.lang.Iterable<? extends com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute> values) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, attributes_);
          onChanged();
        } else {
          attributesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .messages.ItemAttribute attributes = 3;</code>
       */
      public Builder clearAttributes() {
        if (attributesBuilder_ == null) {
          attributes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          attributesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .messages.ItemAttribute attributes = 3;</code>
       */
      public Builder removeAttributes(int index) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.remove(index);
          onChanged();
        } else {
          attributesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .messages.ItemAttribute attributes = 3;</code>
       */
      public com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute.Builder getAttributesBuilder(
          int index) {
        return getAttributesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .messages.ItemAttribute attributes = 3;</code>
       */
      public com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttributeOrBuilder getAttributesOrBuilder(
          int index) {
        if (attributesBuilder_ == null) {
          return attributes_.get(index);  } else {
          return attributesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .messages.ItemAttribute attributes = 3;</code>
       */
      public java.util.List<? extends com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttributeOrBuilder> 
           getAttributesOrBuilderList() {
        if (attributesBuilder_ != null) {
          return attributesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(attributes_);
        }
      }
      /**
       * <code>repeated .messages.ItemAttribute attributes = 3;</code>
       */
      public com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute.Builder addAttributesBuilder() {
        return getAttributesFieldBuilder().addBuilder(
            com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute.getDefaultInstance());
      }
      /**
       * <code>repeated .messages.ItemAttribute attributes = 3;</code>
       */
      public com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute.Builder addAttributesBuilder(
          int index) {
        return getAttributesFieldBuilder().addBuilder(
            index, com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute.getDefaultInstance());
      }
      /**
       * <code>repeated .messages.ItemAttribute attributes = 3;</code>
       */
      public java.util.List<com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute.Builder> 
           getAttributesBuilderList() {
        return getAttributesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute, com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute.Builder, com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttributeOrBuilder> 
          getAttributesFieldBuilder() {
        if (attributesBuilder_ == null) {
          attributesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute, com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute.Builder, com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttributeOrBuilder>(
                  attributes_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          attributes_ = null;
        }
        return attributesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:messages.Item)
    }

    // @@protoc_insertion_point(class_scope:messages.Item)
    private static final com.sm.mmo.moba.network.protobuf.ItemProtos.Item DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sm.mmo.moba.network.protobuf.ItemProtos.Item();
    }

    public static com.sm.mmo.moba.network.protobuf.ItemProtos.Item getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Item>
        PARSER = new com.google.protobuf.AbstractParser<Item>() {
      @java.lang.Override
      public Item parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Item(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Item> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Item> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sm.mmo.moba.network.protobuf.ItemProtos.Item getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ItemSpawnedOrBuilder extends
      // @@protoc_insertion_point(interface_extends:messages.ItemSpawned)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.messages.Position position = 1;</code>
     */
    boolean hasPosition();
    /**
     * <code>.messages.Position position = 1;</code>
     */
    com.sm.mmo.moba.network.protobuf.PositionProtos.Position getPosition();
    /**
     * <code>.messages.Position position = 1;</code>
     */
    com.sm.mmo.moba.network.protobuf.PositionProtos.PositionOrBuilder getPositionOrBuilder();

    /**
     * <code>.messages.Item item = 2;</code>
     */
    boolean hasItem();
    /**
     * <code>.messages.Item item = 2;</code>
     */
    com.sm.mmo.moba.network.protobuf.ItemProtos.Item getItem();
    /**
     * <code>.messages.Item item = 2;</code>
     */
    com.sm.mmo.moba.network.protobuf.ItemProtos.ItemOrBuilder getItemOrBuilder();
  }
  /**
   * Protobuf type {@code messages.ItemSpawned}
   */
  public  static final class ItemSpawned extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:messages.ItemSpawned)
      ItemSpawnedOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ItemSpawned.newBuilder() to construct.
    private ItemSpawned(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ItemSpawned() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ItemSpawned(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.sm.mmo.moba.network.protobuf.PositionProtos.Position.Builder subBuilder = null;
              if (position_ != null) {
                subBuilder = position_.toBuilder();
              }
              position_ = input.readMessage(com.sm.mmo.moba.network.protobuf.PositionProtos.Position.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(position_);
                position_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.sm.mmo.moba.network.protobuf.ItemProtos.Item.Builder subBuilder = null;
              if (item_ != null) {
                subBuilder = item_.toBuilder();
              }
              item_ = input.readMessage(com.sm.mmo.moba.network.protobuf.ItemProtos.Item.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(item_);
                item_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sm.mmo.moba.network.protobuf.ItemProtos.internal_static_messages_ItemSpawned_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sm.mmo.moba.network.protobuf.ItemProtos.internal_static_messages_ItemSpawned_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sm.mmo.moba.network.protobuf.ItemProtos.ItemSpawned.class, com.sm.mmo.moba.network.protobuf.ItemProtos.ItemSpawned.Builder.class);
    }

    public static final int POSITION_FIELD_NUMBER = 1;
    private com.sm.mmo.moba.network.protobuf.PositionProtos.Position position_;
    /**
     * <code>.messages.Position position = 1;</code>
     */
    public boolean hasPosition() {
      return position_ != null;
    }
    /**
     * <code>.messages.Position position = 1;</code>
     */
    public com.sm.mmo.moba.network.protobuf.PositionProtos.Position getPosition() {
      return position_ == null ? com.sm.mmo.moba.network.protobuf.PositionProtos.Position.getDefaultInstance() : position_;
    }
    /**
     * <code>.messages.Position position = 1;</code>
     */
    public com.sm.mmo.moba.network.protobuf.PositionProtos.PositionOrBuilder getPositionOrBuilder() {
      return getPosition();
    }

    public static final int ITEM_FIELD_NUMBER = 2;
    private com.sm.mmo.moba.network.protobuf.ItemProtos.Item item_;
    /**
     * <code>.messages.Item item = 2;</code>
     */
    public boolean hasItem() {
      return item_ != null;
    }
    /**
     * <code>.messages.Item item = 2;</code>
     */
    public com.sm.mmo.moba.network.protobuf.ItemProtos.Item getItem() {
      return item_ == null ? com.sm.mmo.moba.network.protobuf.ItemProtos.Item.getDefaultInstance() : item_;
    }
    /**
     * <code>.messages.Item item = 2;</code>
     */
    public com.sm.mmo.moba.network.protobuf.ItemProtos.ItemOrBuilder getItemOrBuilder() {
      return getItem();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (position_ != null) {
        output.writeMessage(1, getPosition());
      }
      if (item_ != null) {
        output.writeMessage(2, getItem());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (position_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPosition());
      }
      if (item_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getItem());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sm.mmo.moba.network.protobuf.ItemProtos.ItemSpawned)) {
        return super.equals(obj);
      }
      com.sm.mmo.moba.network.protobuf.ItemProtos.ItemSpawned other = (com.sm.mmo.moba.network.protobuf.ItemProtos.ItemSpawned) obj;

      boolean result = true;
      result = result && (hasPosition() == other.hasPosition());
      if (hasPosition()) {
        result = result && getPosition()
            .equals(other.getPosition());
      }
      result = result && (hasItem() == other.hasItem());
      if (hasItem()) {
        result = result && getItem()
            .equals(other.getItem());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPosition()) {
        hash = (37 * hash) + POSITION_FIELD_NUMBER;
        hash = (53 * hash) + getPosition().hashCode();
      }
      if (hasItem()) {
        hash = (37 * hash) + ITEM_FIELD_NUMBER;
        hash = (53 * hash) + getItem().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sm.mmo.moba.network.protobuf.ItemProtos.ItemSpawned parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sm.mmo.moba.network.protobuf.ItemProtos.ItemSpawned parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sm.mmo.moba.network.protobuf.ItemProtos.ItemSpawned parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sm.mmo.moba.network.protobuf.ItemProtos.ItemSpawned parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sm.mmo.moba.network.protobuf.ItemProtos.ItemSpawned parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sm.mmo.moba.network.protobuf.ItemProtos.ItemSpawned parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sm.mmo.moba.network.protobuf.ItemProtos.ItemSpawned parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sm.mmo.moba.network.protobuf.ItemProtos.ItemSpawned parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sm.mmo.moba.network.protobuf.ItemProtos.ItemSpawned parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sm.mmo.moba.network.protobuf.ItemProtos.ItemSpawned parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sm.mmo.moba.network.protobuf.ItemProtos.ItemSpawned parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sm.mmo.moba.network.protobuf.ItemProtos.ItemSpawned parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sm.mmo.moba.network.protobuf.ItemProtos.ItemSpawned prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code messages.ItemSpawned}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:messages.ItemSpawned)
        com.sm.mmo.moba.network.protobuf.ItemProtos.ItemSpawnedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sm.mmo.moba.network.protobuf.ItemProtos.internal_static_messages_ItemSpawned_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sm.mmo.moba.network.protobuf.ItemProtos.internal_static_messages_ItemSpawned_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sm.mmo.moba.network.protobuf.ItemProtos.ItemSpawned.class, com.sm.mmo.moba.network.protobuf.ItemProtos.ItemSpawned.Builder.class);
      }

      // Construct using com.sm.mmo.moba.network.protobuf.ItemProtos.ItemSpawned.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (positionBuilder_ == null) {
          position_ = null;
        } else {
          position_ = null;
          positionBuilder_ = null;
        }
        if (itemBuilder_ == null) {
          item_ = null;
        } else {
          item_ = null;
          itemBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sm.mmo.moba.network.protobuf.ItemProtos.internal_static_messages_ItemSpawned_descriptor;
      }

      @java.lang.Override
      public com.sm.mmo.moba.network.protobuf.ItemProtos.ItemSpawned getDefaultInstanceForType() {
        return com.sm.mmo.moba.network.protobuf.ItemProtos.ItemSpawned.getDefaultInstance();
      }

      @java.lang.Override
      public com.sm.mmo.moba.network.protobuf.ItemProtos.ItemSpawned build() {
        com.sm.mmo.moba.network.protobuf.ItemProtos.ItemSpawned result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sm.mmo.moba.network.protobuf.ItemProtos.ItemSpawned buildPartial() {
        com.sm.mmo.moba.network.protobuf.ItemProtos.ItemSpawned result = new com.sm.mmo.moba.network.protobuf.ItemProtos.ItemSpawned(this);
        if (positionBuilder_ == null) {
          result.position_ = position_;
        } else {
          result.position_ = positionBuilder_.build();
        }
        if (itemBuilder_ == null) {
          result.item_ = item_;
        } else {
          result.item_ = itemBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sm.mmo.moba.network.protobuf.ItemProtos.ItemSpawned) {
          return mergeFrom((com.sm.mmo.moba.network.protobuf.ItemProtos.ItemSpawned)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sm.mmo.moba.network.protobuf.ItemProtos.ItemSpawned other) {
        if (other == com.sm.mmo.moba.network.protobuf.ItemProtos.ItemSpawned.getDefaultInstance()) return this;
        if (other.hasPosition()) {
          mergePosition(other.getPosition());
        }
        if (other.hasItem()) {
          mergeItem(other.getItem());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sm.mmo.moba.network.protobuf.ItemProtos.ItemSpawned parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sm.mmo.moba.network.protobuf.ItemProtos.ItemSpawned) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.sm.mmo.moba.network.protobuf.PositionProtos.Position position_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.sm.mmo.moba.network.protobuf.PositionProtos.Position, com.sm.mmo.moba.network.protobuf.PositionProtos.Position.Builder, com.sm.mmo.moba.network.protobuf.PositionProtos.PositionOrBuilder> positionBuilder_;
      /**
       * <code>.messages.Position position = 1;</code>
       */
      public boolean hasPosition() {
        return positionBuilder_ != null || position_ != null;
      }
      /**
       * <code>.messages.Position position = 1;</code>
       */
      public com.sm.mmo.moba.network.protobuf.PositionProtos.Position getPosition() {
        if (positionBuilder_ == null) {
          return position_ == null ? com.sm.mmo.moba.network.protobuf.PositionProtos.Position.getDefaultInstance() : position_;
        } else {
          return positionBuilder_.getMessage();
        }
      }
      /**
       * <code>.messages.Position position = 1;</code>
       */
      public Builder setPosition(com.sm.mmo.moba.network.protobuf.PositionProtos.Position value) {
        if (positionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          position_ = value;
          onChanged();
        } else {
          positionBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.messages.Position position = 1;</code>
       */
      public Builder setPosition(
          com.sm.mmo.moba.network.protobuf.PositionProtos.Position.Builder builderForValue) {
        if (positionBuilder_ == null) {
          position_ = builderForValue.build();
          onChanged();
        } else {
          positionBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.messages.Position position = 1;</code>
       */
      public Builder mergePosition(com.sm.mmo.moba.network.protobuf.PositionProtos.Position value) {
        if (positionBuilder_ == null) {
          if (position_ != null) {
            position_ =
              com.sm.mmo.moba.network.protobuf.PositionProtos.Position.newBuilder(position_).mergeFrom(value).buildPartial();
          } else {
            position_ = value;
          }
          onChanged();
        } else {
          positionBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.messages.Position position = 1;</code>
       */
      public Builder clearPosition() {
        if (positionBuilder_ == null) {
          position_ = null;
          onChanged();
        } else {
          position_ = null;
          positionBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.messages.Position position = 1;</code>
       */
      public com.sm.mmo.moba.network.protobuf.PositionProtos.Position.Builder getPositionBuilder() {
        
        onChanged();
        return getPositionFieldBuilder().getBuilder();
      }
      /**
       * <code>.messages.Position position = 1;</code>
       */
      public com.sm.mmo.moba.network.protobuf.PositionProtos.PositionOrBuilder getPositionOrBuilder() {
        if (positionBuilder_ != null) {
          return positionBuilder_.getMessageOrBuilder();
        } else {
          return position_ == null ?
              com.sm.mmo.moba.network.protobuf.PositionProtos.Position.getDefaultInstance() : position_;
        }
      }
      /**
       * <code>.messages.Position position = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.sm.mmo.moba.network.protobuf.PositionProtos.Position, com.sm.mmo.moba.network.protobuf.PositionProtos.Position.Builder, com.sm.mmo.moba.network.protobuf.PositionProtos.PositionOrBuilder> 
          getPositionFieldBuilder() {
        if (positionBuilder_ == null) {
          positionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.sm.mmo.moba.network.protobuf.PositionProtos.Position, com.sm.mmo.moba.network.protobuf.PositionProtos.Position.Builder, com.sm.mmo.moba.network.protobuf.PositionProtos.PositionOrBuilder>(
                  getPosition(),
                  getParentForChildren(),
                  isClean());
          position_ = null;
        }
        return positionBuilder_;
      }

      private com.sm.mmo.moba.network.protobuf.ItemProtos.Item item_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.sm.mmo.moba.network.protobuf.ItemProtos.Item, com.sm.mmo.moba.network.protobuf.ItemProtos.Item.Builder, com.sm.mmo.moba.network.protobuf.ItemProtos.ItemOrBuilder> itemBuilder_;
      /**
       * <code>.messages.Item item = 2;</code>
       */
      public boolean hasItem() {
        return itemBuilder_ != null || item_ != null;
      }
      /**
       * <code>.messages.Item item = 2;</code>
       */
      public com.sm.mmo.moba.network.protobuf.ItemProtos.Item getItem() {
        if (itemBuilder_ == null) {
          return item_ == null ? com.sm.mmo.moba.network.protobuf.ItemProtos.Item.getDefaultInstance() : item_;
        } else {
          return itemBuilder_.getMessage();
        }
      }
      /**
       * <code>.messages.Item item = 2;</code>
       */
      public Builder setItem(com.sm.mmo.moba.network.protobuf.ItemProtos.Item value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          item_ = value;
          onChanged();
        } else {
          itemBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.messages.Item item = 2;</code>
       */
      public Builder setItem(
          com.sm.mmo.moba.network.protobuf.ItemProtos.Item.Builder builderForValue) {
        if (itemBuilder_ == null) {
          item_ = builderForValue.build();
          onChanged();
        } else {
          itemBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.messages.Item item = 2;</code>
       */
      public Builder mergeItem(com.sm.mmo.moba.network.protobuf.ItemProtos.Item value) {
        if (itemBuilder_ == null) {
          if (item_ != null) {
            item_ =
              com.sm.mmo.moba.network.protobuf.ItemProtos.Item.newBuilder(item_).mergeFrom(value).buildPartial();
          } else {
            item_ = value;
          }
          onChanged();
        } else {
          itemBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.messages.Item item = 2;</code>
       */
      public Builder clearItem() {
        if (itemBuilder_ == null) {
          item_ = null;
          onChanged();
        } else {
          item_ = null;
          itemBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.messages.Item item = 2;</code>
       */
      public com.sm.mmo.moba.network.protobuf.ItemProtos.Item.Builder getItemBuilder() {
        
        onChanged();
        return getItemFieldBuilder().getBuilder();
      }
      /**
       * <code>.messages.Item item = 2;</code>
       */
      public com.sm.mmo.moba.network.protobuf.ItemProtos.ItemOrBuilder getItemOrBuilder() {
        if (itemBuilder_ != null) {
          return itemBuilder_.getMessageOrBuilder();
        } else {
          return item_ == null ?
              com.sm.mmo.moba.network.protobuf.ItemProtos.Item.getDefaultInstance() : item_;
        }
      }
      /**
       * <code>.messages.Item item = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.sm.mmo.moba.network.protobuf.ItemProtos.Item, com.sm.mmo.moba.network.protobuf.ItemProtos.Item.Builder, com.sm.mmo.moba.network.protobuf.ItemProtos.ItemOrBuilder> 
          getItemFieldBuilder() {
        if (itemBuilder_ == null) {
          itemBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.sm.mmo.moba.network.protobuf.ItemProtos.Item, com.sm.mmo.moba.network.protobuf.ItemProtos.Item.Builder, com.sm.mmo.moba.network.protobuf.ItemProtos.ItemOrBuilder>(
                  getItem(),
                  getParentForChildren(),
                  isClean());
          item_ = null;
        }
        return itemBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:messages.ItemSpawned)
    }

    // @@protoc_insertion_point(class_scope:messages.ItemSpawned)
    private static final com.sm.mmo.moba.network.protobuf.ItemProtos.ItemSpawned DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sm.mmo.moba.network.protobuf.ItemProtos.ItemSpawned();
    }

    public static com.sm.mmo.moba.network.protobuf.ItemProtos.ItemSpawned getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ItemSpawned>
        PARSER = new com.google.protobuf.AbstractParser<ItemSpawned>() {
      @java.lang.Override
      public ItemSpawned parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ItemSpawned(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ItemSpawned> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ItemSpawned> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sm.mmo.moba.network.protobuf.ItemProtos.ItemSpawned getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ItemAttributeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:messages.ItemAttribute)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *speed, attack damage, magic
     * </pre>
     *
     * <code>int32 attribute = 1;</code>
     */
    int getAttribute();

    /**
     * <code>bool boolVal = 2;</code>
     */
    boolean getBoolVal();

    /**
     * <code>int32 intVal = 3;</code>
     */
    int getIntVal();

    /**
     * <code>float floatVal = 4;</code>
     */
    float getFloatVal();

    /**
     * <code>string stringVal = 5;</code>
     */
    java.lang.String getStringVal();
    /**
     * <code>string stringVal = 5;</code>
     */
    com.google.protobuf.ByteString
        getStringValBytes();

    public com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute.ValueCase getValueCase();
  }
  /**
   * Protobuf type {@code messages.ItemAttribute}
   */
  public  static final class ItemAttribute extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:messages.ItemAttribute)
      ItemAttributeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ItemAttribute.newBuilder() to construct.
    private ItemAttribute(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ItemAttribute() {
      attribute_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ItemAttribute(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              attribute_ = input.readInt32();
              break;
            }
            case 16: {
              valueCase_ = 2;
              value_ = input.readBool();
              break;
            }
            case 24: {
              valueCase_ = 3;
              value_ = input.readInt32();
              break;
            }
            case 37: {
              valueCase_ = 4;
              value_ = input.readFloat();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              valueCase_ = 5;
              value_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sm.mmo.moba.network.protobuf.ItemProtos.internal_static_messages_ItemAttribute_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sm.mmo.moba.network.protobuf.ItemProtos.internal_static_messages_ItemAttribute_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute.class, com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute.Builder.class);
    }

    private int valueCase_ = 0;
    private java.lang.Object value_;
    public enum ValueCase
        implements com.google.protobuf.Internal.EnumLite {
      BOOLVAL(2),
      INTVAL(3),
      FLOATVAL(4),
      STRINGVAL(5),
      VALUE_NOT_SET(0);
      private final int value;
      private ValueCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ValueCase valueOf(int value) {
        return forNumber(value);
      }

      public static ValueCase forNumber(int value) {
        switch (value) {
          case 2: return BOOLVAL;
          case 3: return INTVAL;
          case 4: return FLOATVAL;
          case 5: return STRINGVAL;
          case 0: return VALUE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public ValueCase
    getValueCase() {
      return ValueCase.forNumber(
          valueCase_);
    }

    public static final int ATTRIBUTE_FIELD_NUMBER = 1;
    private int attribute_;
    /**
     * <pre>
     *speed, attack damage, magic
     * </pre>
     *
     * <code>int32 attribute = 1;</code>
     */
    public int getAttribute() {
      return attribute_;
    }

    public static final int BOOLVAL_FIELD_NUMBER = 2;
    /**
     * <code>bool boolVal = 2;</code>
     */
    public boolean getBoolVal() {
      if (valueCase_ == 2) {
        return (java.lang.Boolean) value_;
      }
      return false;
    }

    public static final int INTVAL_FIELD_NUMBER = 3;
    /**
     * <code>int32 intVal = 3;</code>
     */
    public int getIntVal() {
      if (valueCase_ == 3) {
        return (java.lang.Integer) value_;
      }
      return 0;
    }

    public static final int FLOATVAL_FIELD_NUMBER = 4;
    /**
     * <code>float floatVal = 4;</code>
     */
    public float getFloatVal() {
      if (valueCase_ == 4) {
        return (java.lang.Float) value_;
      }
      return 0F;
    }

    public static final int STRINGVAL_FIELD_NUMBER = 5;
    /**
     * <code>string stringVal = 5;</code>
     */
    public java.lang.String getStringVal() {
      java.lang.Object ref = "";
      if (valueCase_ == 5) {
        ref = value_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (valueCase_ == 5) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string stringVal = 5;</code>
     */
    public com.google.protobuf.ByteString
        getStringValBytes() {
      java.lang.Object ref = "";
      if (valueCase_ == 5) {
        ref = value_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (valueCase_ == 5) {
          value_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (attribute_ != 0) {
        output.writeInt32(1, attribute_);
      }
      if (valueCase_ == 2) {
        output.writeBool(
            2, (boolean)((java.lang.Boolean) value_));
      }
      if (valueCase_ == 3) {
        output.writeInt32(
            3, (int)((java.lang.Integer) value_));
      }
      if (valueCase_ == 4) {
        output.writeFloat(
            4, (float)((java.lang.Float) value_));
      }
      if (valueCase_ == 5) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, value_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (attribute_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, attribute_);
      }
      if (valueCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(
              2, (boolean)((java.lang.Boolean) value_));
      }
      if (valueCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(
              3, (int)((java.lang.Integer) value_));
      }
      if (valueCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(
              4, (float)((java.lang.Float) value_));
      }
      if (valueCase_ == 5) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, value_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute)) {
        return super.equals(obj);
      }
      com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute other = (com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute) obj;

      boolean result = true;
      result = result && (getAttribute()
          == other.getAttribute());
      result = result && getValueCase().equals(
          other.getValueCase());
      if (!result) return false;
      switch (valueCase_) {
        case 2:
          result = result && (getBoolVal()
              == other.getBoolVal());
          break;
        case 3:
          result = result && (getIntVal()
              == other.getIntVal());
          break;
        case 4:
          result = result && (
              java.lang.Float.floatToIntBits(getFloatVal())
              == java.lang.Float.floatToIntBits(
                  other.getFloatVal()));
          break;
        case 5:
          result = result && getStringVal()
              .equals(other.getStringVal());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ATTRIBUTE_FIELD_NUMBER;
      hash = (53 * hash) + getAttribute();
      switch (valueCase_) {
        case 2:
          hash = (37 * hash) + BOOLVAL_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
              getBoolVal());
          break;
        case 3:
          hash = (37 * hash) + INTVAL_FIELD_NUMBER;
          hash = (53 * hash) + getIntVal();
          break;
        case 4:
          hash = (37 * hash) + FLOATVAL_FIELD_NUMBER;
          hash = (53 * hash) + java.lang.Float.floatToIntBits(
              getFloatVal());
          break;
        case 5:
          hash = (37 * hash) + STRINGVAL_FIELD_NUMBER;
          hash = (53 * hash) + getStringVal().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code messages.ItemAttribute}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:messages.ItemAttribute)
        com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttributeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sm.mmo.moba.network.protobuf.ItemProtos.internal_static_messages_ItemAttribute_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sm.mmo.moba.network.protobuf.ItemProtos.internal_static_messages_ItemAttribute_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute.class, com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute.Builder.class);
      }

      // Construct using com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        attribute_ = 0;

        valueCase_ = 0;
        value_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sm.mmo.moba.network.protobuf.ItemProtos.internal_static_messages_ItemAttribute_descriptor;
      }

      @java.lang.Override
      public com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute getDefaultInstanceForType() {
        return com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute.getDefaultInstance();
      }

      @java.lang.Override
      public com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute build() {
        com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute buildPartial() {
        com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute result = new com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute(this);
        result.attribute_ = attribute_;
        if (valueCase_ == 2) {
          result.value_ = value_;
        }
        if (valueCase_ == 3) {
          result.value_ = value_;
        }
        if (valueCase_ == 4) {
          result.value_ = value_;
        }
        if (valueCase_ == 5) {
          result.value_ = value_;
        }
        result.valueCase_ = valueCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute) {
          return mergeFrom((com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute other) {
        if (other == com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute.getDefaultInstance()) return this;
        if (other.getAttribute() != 0) {
          setAttribute(other.getAttribute());
        }
        switch (other.getValueCase()) {
          case BOOLVAL: {
            setBoolVal(other.getBoolVal());
            break;
          }
          case INTVAL: {
            setIntVal(other.getIntVal());
            break;
          }
          case FLOATVAL: {
            setFloatVal(other.getFloatVal());
            break;
          }
          case STRINGVAL: {
            valueCase_ = 5;
            value_ = other.value_;
            onChanged();
            break;
          }
          case VALUE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int valueCase_ = 0;
      private java.lang.Object value_;
      public ValueCase
          getValueCase() {
        return ValueCase.forNumber(
            valueCase_);
      }

      public Builder clearValue() {
        valueCase_ = 0;
        value_ = null;
        onChanged();
        return this;
      }


      private int attribute_ ;
      /**
       * <pre>
       *speed, attack damage, magic
       * </pre>
       *
       * <code>int32 attribute = 1;</code>
       */
      public int getAttribute() {
        return attribute_;
      }
      /**
       * <pre>
       *speed, attack damage, magic
       * </pre>
       *
       * <code>int32 attribute = 1;</code>
       */
      public Builder setAttribute(int value) {
        
        attribute_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *speed, attack damage, magic
       * </pre>
       *
       * <code>int32 attribute = 1;</code>
       */
      public Builder clearAttribute() {
        
        attribute_ = 0;
        onChanged();
        return this;
      }

      /**
       * <code>bool boolVal = 2;</code>
       */
      public boolean getBoolVal() {
        if (valueCase_ == 2) {
          return (java.lang.Boolean) value_;
        }
        return false;
      }
      /**
       * <code>bool boolVal = 2;</code>
       */
      public Builder setBoolVal(boolean value) {
        valueCase_ = 2;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool boolVal = 2;</code>
       */
      public Builder clearBoolVal() {
        if (valueCase_ == 2) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>int32 intVal = 3;</code>
       */
      public int getIntVal() {
        if (valueCase_ == 3) {
          return (java.lang.Integer) value_;
        }
        return 0;
      }
      /**
       * <code>int32 intVal = 3;</code>
       */
      public Builder setIntVal(int value) {
        valueCase_ = 3;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 intVal = 3;</code>
       */
      public Builder clearIntVal() {
        if (valueCase_ == 3) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>float floatVal = 4;</code>
       */
      public float getFloatVal() {
        if (valueCase_ == 4) {
          return (java.lang.Float) value_;
        }
        return 0F;
      }
      /**
       * <code>float floatVal = 4;</code>
       */
      public Builder setFloatVal(float value) {
        valueCase_ = 4;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float floatVal = 4;</code>
       */
      public Builder clearFloatVal() {
        if (valueCase_ == 4) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>string stringVal = 5;</code>
       */
      public java.lang.String getStringVal() {
        java.lang.Object ref = "";
        if (valueCase_ == 5) {
          ref = value_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (valueCase_ == 5) {
            value_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string stringVal = 5;</code>
       */
      public com.google.protobuf.ByteString
          getStringValBytes() {
        java.lang.Object ref = "";
        if (valueCase_ == 5) {
          ref = value_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (valueCase_ == 5) {
            value_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string stringVal = 5;</code>
       */
      public Builder setStringVal(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  valueCase_ = 5;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string stringVal = 5;</code>
       */
      public Builder clearStringVal() {
        if (valueCase_ == 5) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>string stringVal = 5;</code>
       */
      public Builder setStringValBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        valueCase_ = 5;
        value_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:messages.ItemAttribute)
    }

    // @@protoc_insertion_point(class_scope:messages.ItemAttribute)
    private static final com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute();
    }

    public static com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ItemAttribute>
        PARSER = new com.google.protobuf.AbstractParser<ItemAttribute>() {
      @java.lang.Override
      public ItemAttribute parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ItemAttribute(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ItemAttribute> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ItemAttribute> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sm.mmo.moba.network.protobuf.ItemProtos.ItemAttribute getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_Item_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_messages_Item_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_ItemSpawned_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_messages_ItemSpawned_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_ItemAttribute_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_messages_ItemAttribute_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013items.proto\022\010messages\032\017positions.proto" +
      "\"M\n\004Item\022\n\n\002id\030\001 \001(\005\022\014\n\004type\030\002 \001(\005\022+\n\nat" +
      "tributes\030\003 \003(\0132\027.messages.ItemAttribute\"" +
      "Q\n\013ItemSpawned\022$\n\010position\030\001 \001(\0132\022.messa" +
      "ges.Position\022\034\n\004item\030\002 \001(\0132\016.messages.It" +
      "em\"y\n\rItemAttribute\022\021\n\tattribute\030\001 \001(\005\022\021" +
      "\n\007boolVal\030\002 \001(\010H\000\022\020\n\006intVal\030\003 \001(\005H\000\022\022\n\010f" +
      "loatVal\030\004 \001(\002H\000\022\023\n\tstringVal\030\005 \001(\tH\000B\007\n\005" +
      "valueB.\n com.sm.mmo.moba.network.protobu" +
      "fB\nItemProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.sm.mmo.moba.network.protobuf.PositionProtos.getDescriptor(),
        }, assigner);
    internal_static_messages_Item_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_messages_Item_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_messages_Item_descriptor,
        new java.lang.String[] { "Id", "Type", "Attributes", });
    internal_static_messages_ItemSpawned_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_messages_ItemSpawned_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_messages_ItemSpawned_descriptor,
        new java.lang.String[] { "Position", "Item", });
    internal_static_messages_ItemAttribute_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_messages_ItemAttribute_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_messages_ItemAttribute_descriptor,
        new java.lang.String[] { "Attribute", "BoolVal", "IntVal", "FloatVal", "StringVal", "Value", });
    com.sm.mmo.moba.network.protobuf.PositionProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
