// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: players.proto

package com.sm.mmo.moba.network.protobuf;

public final class PlayerProtos {
  private PlayerProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PlayerConnectedOrBuilder extends
      // @@protoc_insertion_point(interface_extends:messages.PlayerConnected)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>.messages.EntitySpawned entitySpawned = 8;</code>
     */
    boolean hasEntitySpawned();
    /**
     * <code>.messages.EntitySpawned entitySpawned = 8;</code>
     */
    com.sm.mmo.moba.network.protobuf.EntityProtos.EntitySpawned getEntitySpawned();
    /**
     * <code>.messages.EntitySpawned entitySpawned = 8;</code>
     */
    com.sm.mmo.moba.network.protobuf.EntityProtos.EntitySpawnedOrBuilder getEntitySpawnedOrBuilder();
  }
  /**
   * Protobuf type {@code messages.PlayerConnected}
   */
  public  static final class PlayerConnected extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:messages.PlayerConnected)
      PlayerConnectedOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PlayerConnected.newBuilder() to construct.
    private PlayerConnected(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayerConnected() {
      id_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerConnected(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 66: {
              com.sm.mmo.moba.network.protobuf.EntityProtos.EntitySpawned.Builder subBuilder = null;
              if (entitySpawned_ != null) {
                subBuilder = entitySpawned_.toBuilder();
              }
              entitySpawned_ = input.readMessage(com.sm.mmo.moba.network.protobuf.EntityProtos.EntitySpawned.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(entitySpawned_);
                entitySpawned_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sm.mmo.moba.network.protobuf.PlayerProtos.internal_static_messages_PlayerConnected_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sm.mmo.moba.network.protobuf.PlayerProtos.internal_static_messages_PlayerConnected_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sm.mmo.moba.network.protobuf.PlayerProtos.PlayerConnected.class, com.sm.mmo.moba.network.protobuf.PlayerProtos.PlayerConnected.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int ENTITYSPAWNED_FIELD_NUMBER = 8;
    private com.sm.mmo.moba.network.protobuf.EntityProtos.EntitySpawned entitySpawned_;
    /**
     * <code>.messages.EntitySpawned entitySpawned = 8;</code>
     */
    public boolean hasEntitySpawned() {
      return entitySpawned_ != null;
    }
    /**
     * <code>.messages.EntitySpawned entitySpawned = 8;</code>
     */
    public com.sm.mmo.moba.network.protobuf.EntityProtos.EntitySpawned getEntitySpawned() {
      return entitySpawned_ == null ? com.sm.mmo.moba.network.protobuf.EntityProtos.EntitySpawned.getDefaultInstance() : entitySpawned_;
    }
    /**
     * <code>.messages.EntitySpawned entitySpawned = 8;</code>
     */
    public com.sm.mmo.moba.network.protobuf.EntityProtos.EntitySpawnedOrBuilder getEntitySpawnedOrBuilder() {
      return getEntitySpawned();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (entitySpawned_ != null) {
        output.writeMessage(8, getEntitySpawned());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (entitySpawned_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getEntitySpawned());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sm.mmo.moba.network.protobuf.PlayerProtos.PlayerConnected)) {
        return super.equals(obj);
      }
      com.sm.mmo.moba.network.protobuf.PlayerProtos.PlayerConnected other = (com.sm.mmo.moba.network.protobuf.PlayerProtos.PlayerConnected) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && (hasEntitySpawned() == other.hasEntitySpawned());
      if (hasEntitySpawned()) {
        result = result && getEntitySpawned()
            .equals(other.getEntitySpawned());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      if (hasEntitySpawned()) {
        hash = (37 * hash) + ENTITYSPAWNED_FIELD_NUMBER;
        hash = (53 * hash) + getEntitySpawned().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sm.mmo.moba.network.protobuf.PlayerProtos.PlayerConnected parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sm.mmo.moba.network.protobuf.PlayerProtos.PlayerConnected parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sm.mmo.moba.network.protobuf.PlayerProtos.PlayerConnected parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sm.mmo.moba.network.protobuf.PlayerProtos.PlayerConnected parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sm.mmo.moba.network.protobuf.PlayerProtos.PlayerConnected parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sm.mmo.moba.network.protobuf.PlayerProtos.PlayerConnected parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sm.mmo.moba.network.protobuf.PlayerProtos.PlayerConnected parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sm.mmo.moba.network.protobuf.PlayerProtos.PlayerConnected parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sm.mmo.moba.network.protobuf.PlayerProtos.PlayerConnected parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sm.mmo.moba.network.protobuf.PlayerProtos.PlayerConnected parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sm.mmo.moba.network.protobuf.PlayerProtos.PlayerConnected parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sm.mmo.moba.network.protobuf.PlayerProtos.PlayerConnected parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sm.mmo.moba.network.protobuf.PlayerProtos.PlayerConnected prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code messages.PlayerConnected}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:messages.PlayerConnected)
        com.sm.mmo.moba.network.protobuf.PlayerProtos.PlayerConnectedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sm.mmo.moba.network.protobuf.PlayerProtos.internal_static_messages_PlayerConnected_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sm.mmo.moba.network.protobuf.PlayerProtos.internal_static_messages_PlayerConnected_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sm.mmo.moba.network.protobuf.PlayerProtos.PlayerConnected.class, com.sm.mmo.moba.network.protobuf.PlayerProtos.PlayerConnected.Builder.class);
      }

      // Construct using com.sm.mmo.moba.network.protobuf.PlayerProtos.PlayerConnected.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        if (entitySpawnedBuilder_ == null) {
          entitySpawned_ = null;
        } else {
          entitySpawned_ = null;
          entitySpawnedBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sm.mmo.moba.network.protobuf.PlayerProtos.internal_static_messages_PlayerConnected_descriptor;
      }

      @java.lang.Override
      public com.sm.mmo.moba.network.protobuf.PlayerProtos.PlayerConnected getDefaultInstanceForType() {
        return com.sm.mmo.moba.network.protobuf.PlayerProtos.PlayerConnected.getDefaultInstance();
      }

      @java.lang.Override
      public com.sm.mmo.moba.network.protobuf.PlayerProtos.PlayerConnected build() {
        com.sm.mmo.moba.network.protobuf.PlayerProtos.PlayerConnected result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sm.mmo.moba.network.protobuf.PlayerProtos.PlayerConnected buildPartial() {
        com.sm.mmo.moba.network.protobuf.PlayerProtos.PlayerConnected result = new com.sm.mmo.moba.network.protobuf.PlayerProtos.PlayerConnected(this);
        result.id_ = id_;
        if (entitySpawnedBuilder_ == null) {
          result.entitySpawned_ = entitySpawned_;
        } else {
          result.entitySpawned_ = entitySpawnedBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sm.mmo.moba.network.protobuf.PlayerProtos.PlayerConnected) {
          return mergeFrom((com.sm.mmo.moba.network.protobuf.PlayerProtos.PlayerConnected)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sm.mmo.moba.network.protobuf.PlayerProtos.PlayerConnected other) {
        if (other == com.sm.mmo.moba.network.protobuf.PlayerProtos.PlayerConnected.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.hasEntitySpawned()) {
          mergeEntitySpawned(other.getEntitySpawned());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sm.mmo.moba.network.protobuf.PlayerProtos.PlayerConnected parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sm.mmo.moba.network.protobuf.PlayerProtos.PlayerConnected) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private com.sm.mmo.moba.network.protobuf.EntityProtos.EntitySpawned entitySpawned_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.sm.mmo.moba.network.protobuf.EntityProtos.EntitySpawned, com.sm.mmo.moba.network.protobuf.EntityProtos.EntitySpawned.Builder, com.sm.mmo.moba.network.protobuf.EntityProtos.EntitySpawnedOrBuilder> entitySpawnedBuilder_;
      /**
       * <code>.messages.EntitySpawned entitySpawned = 8;</code>
       */
      public boolean hasEntitySpawned() {
        return entitySpawnedBuilder_ != null || entitySpawned_ != null;
      }
      /**
       * <code>.messages.EntitySpawned entitySpawned = 8;</code>
       */
      public com.sm.mmo.moba.network.protobuf.EntityProtos.EntitySpawned getEntitySpawned() {
        if (entitySpawnedBuilder_ == null) {
          return entitySpawned_ == null ? com.sm.mmo.moba.network.protobuf.EntityProtos.EntitySpawned.getDefaultInstance() : entitySpawned_;
        } else {
          return entitySpawnedBuilder_.getMessage();
        }
      }
      /**
       * <code>.messages.EntitySpawned entitySpawned = 8;</code>
       */
      public Builder setEntitySpawned(com.sm.mmo.moba.network.protobuf.EntityProtos.EntitySpawned value) {
        if (entitySpawnedBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          entitySpawned_ = value;
          onChanged();
        } else {
          entitySpawnedBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.messages.EntitySpawned entitySpawned = 8;</code>
       */
      public Builder setEntitySpawned(
          com.sm.mmo.moba.network.protobuf.EntityProtos.EntitySpawned.Builder builderForValue) {
        if (entitySpawnedBuilder_ == null) {
          entitySpawned_ = builderForValue.build();
          onChanged();
        } else {
          entitySpawnedBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.messages.EntitySpawned entitySpawned = 8;</code>
       */
      public Builder mergeEntitySpawned(com.sm.mmo.moba.network.protobuf.EntityProtos.EntitySpawned value) {
        if (entitySpawnedBuilder_ == null) {
          if (entitySpawned_ != null) {
            entitySpawned_ =
              com.sm.mmo.moba.network.protobuf.EntityProtos.EntitySpawned.newBuilder(entitySpawned_).mergeFrom(value).buildPartial();
          } else {
            entitySpawned_ = value;
          }
          onChanged();
        } else {
          entitySpawnedBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.messages.EntitySpawned entitySpawned = 8;</code>
       */
      public Builder clearEntitySpawned() {
        if (entitySpawnedBuilder_ == null) {
          entitySpawned_ = null;
          onChanged();
        } else {
          entitySpawned_ = null;
          entitySpawnedBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.messages.EntitySpawned entitySpawned = 8;</code>
       */
      public com.sm.mmo.moba.network.protobuf.EntityProtos.EntitySpawned.Builder getEntitySpawnedBuilder() {
        
        onChanged();
        return getEntitySpawnedFieldBuilder().getBuilder();
      }
      /**
       * <code>.messages.EntitySpawned entitySpawned = 8;</code>
       */
      public com.sm.mmo.moba.network.protobuf.EntityProtos.EntitySpawnedOrBuilder getEntitySpawnedOrBuilder() {
        if (entitySpawnedBuilder_ != null) {
          return entitySpawnedBuilder_.getMessageOrBuilder();
        } else {
          return entitySpawned_ == null ?
              com.sm.mmo.moba.network.protobuf.EntityProtos.EntitySpawned.getDefaultInstance() : entitySpawned_;
        }
      }
      /**
       * <code>.messages.EntitySpawned entitySpawned = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.sm.mmo.moba.network.protobuf.EntityProtos.EntitySpawned, com.sm.mmo.moba.network.protobuf.EntityProtos.EntitySpawned.Builder, com.sm.mmo.moba.network.protobuf.EntityProtos.EntitySpawnedOrBuilder> 
          getEntitySpawnedFieldBuilder() {
        if (entitySpawnedBuilder_ == null) {
          entitySpawnedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.sm.mmo.moba.network.protobuf.EntityProtos.EntitySpawned, com.sm.mmo.moba.network.protobuf.EntityProtos.EntitySpawned.Builder, com.sm.mmo.moba.network.protobuf.EntityProtos.EntitySpawnedOrBuilder>(
                  getEntitySpawned(),
                  getParentForChildren(),
                  isClean());
          entitySpawned_ = null;
        }
        return entitySpawnedBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:messages.PlayerConnected)
    }

    // @@protoc_insertion_point(class_scope:messages.PlayerConnected)
    private static final com.sm.mmo.moba.network.protobuf.PlayerProtos.PlayerConnected DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sm.mmo.moba.network.protobuf.PlayerProtos.PlayerConnected();
    }

    public static com.sm.mmo.moba.network.protobuf.PlayerProtos.PlayerConnected getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerConnected>
        PARSER = new com.google.protobuf.AbstractParser<PlayerConnected>() {
      @java.lang.Override
      public PlayerConnected parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerConnected(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlayerConnected> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerConnected> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sm.mmo.moba.network.protobuf.PlayerProtos.PlayerConnected getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_PlayerConnected_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_messages_PlayerConnected_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rplayers.proto\022\010messages\032\016entities.prot" +
      "o\"M\n\017PlayerConnected\022\n\n\002id\030\001 \001(\005\022.\n\renti" +
      "tySpawned\030\010 \001(\0132\027.messages.EntitySpawned" +
      "B0\n com.sm.mmo.moba.network.protobufB\014Pl" +
      "ayerProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.sm.mmo.moba.network.protobuf.EntityProtos.getDescriptor(),
        }, assigner);
    internal_static_messages_PlayerConnected_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_messages_PlayerConnected_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_messages_PlayerConnected_descriptor,
        new java.lang.String[] { "Id", "EntitySpawned", });
    com.sm.mmo.moba.network.protobuf.EntityProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
