// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: positions.proto

package com.sm.mmo.moba.network.protobuf;

public final class PositionProtos {
  private PositionProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PositionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:messages.Position)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>sint32 x = 3;</code>
     */
    int getX();

    /**
     * <code>sint32 y = 4;</code>
     */
    int getY();

    /**
     * <code>sint32 z = 5;</code>
     */
    int getZ();

    /**
     * <code>int32 angle = 6;</code>
     */
    int getAngle();
  }
  /**
   * Protobuf type {@code messages.Position}
   */
  public  static final class Position extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:messages.Position)
      PositionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Position.newBuilder() to construct.
    private Position(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Position() {
      x_ = 0;
      y_ = 0;
      z_ = 0;
      angle_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Position(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 24: {

              x_ = input.readSInt32();
              break;
            }
            case 32: {

              y_ = input.readSInt32();
              break;
            }
            case 40: {

              z_ = input.readSInt32();
              break;
            }
            case 48: {

              angle_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sm.mmo.moba.network.protobuf.PositionProtos.internal_static_messages_Position_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sm.mmo.moba.network.protobuf.PositionProtos.internal_static_messages_Position_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sm.mmo.moba.network.protobuf.PositionProtos.Position.class, com.sm.mmo.moba.network.protobuf.PositionProtos.Position.Builder.class);
    }

    public static final int X_FIELD_NUMBER = 3;
    private int x_;
    /**
     * <code>sint32 x = 3;</code>
     */
    public int getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 4;
    private int y_;
    /**
     * <code>sint32 y = 4;</code>
     */
    public int getY() {
      return y_;
    }

    public static final int Z_FIELD_NUMBER = 5;
    private int z_;
    /**
     * <code>sint32 z = 5;</code>
     */
    public int getZ() {
      return z_;
    }

    public static final int ANGLE_FIELD_NUMBER = 6;
    private int angle_;
    /**
     * <code>int32 angle = 6;</code>
     */
    public int getAngle() {
      return angle_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (x_ != 0) {
        output.writeSInt32(3, x_);
      }
      if (y_ != 0) {
        output.writeSInt32(4, y_);
      }
      if (z_ != 0) {
        output.writeSInt32(5, z_);
      }
      if (angle_ != 0) {
        output.writeInt32(6, angle_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (x_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(3, x_);
      }
      if (y_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(4, y_);
      }
      if (z_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(5, z_);
      }
      if (angle_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, angle_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sm.mmo.moba.network.protobuf.PositionProtos.Position)) {
        return super.equals(obj);
      }
      com.sm.mmo.moba.network.protobuf.PositionProtos.Position other = (com.sm.mmo.moba.network.protobuf.PositionProtos.Position) obj;

      boolean result = true;
      result = result && (getX()
          == other.getX());
      result = result && (getY()
          == other.getY());
      result = result && (getZ()
          == other.getZ());
      result = result && (getAngle()
          == other.getAngle());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + getX();
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + getY();
      hash = (37 * hash) + Z_FIELD_NUMBER;
      hash = (53 * hash) + getZ();
      hash = (37 * hash) + ANGLE_FIELD_NUMBER;
      hash = (53 * hash) + getAngle();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sm.mmo.moba.network.protobuf.PositionProtos.Position parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sm.mmo.moba.network.protobuf.PositionProtos.Position parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sm.mmo.moba.network.protobuf.PositionProtos.Position parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sm.mmo.moba.network.protobuf.PositionProtos.Position parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sm.mmo.moba.network.protobuf.PositionProtos.Position parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sm.mmo.moba.network.protobuf.PositionProtos.Position parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sm.mmo.moba.network.protobuf.PositionProtos.Position parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sm.mmo.moba.network.protobuf.PositionProtos.Position parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sm.mmo.moba.network.protobuf.PositionProtos.Position parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sm.mmo.moba.network.protobuf.PositionProtos.Position parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sm.mmo.moba.network.protobuf.PositionProtos.Position parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sm.mmo.moba.network.protobuf.PositionProtos.Position parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sm.mmo.moba.network.protobuf.PositionProtos.Position prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code messages.Position}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:messages.Position)
        com.sm.mmo.moba.network.protobuf.PositionProtos.PositionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sm.mmo.moba.network.protobuf.PositionProtos.internal_static_messages_Position_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sm.mmo.moba.network.protobuf.PositionProtos.internal_static_messages_Position_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sm.mmo.moba.network.protobuf.PositionProtos.Position.class, com.sm.mmo.moba.network.protobuf.PositionProtos.Position.Builder.class);
      }

      // Construct using com.sm.mmo.moba.network.protobuf.PositionProtos.Position.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        x_ = 0;

        y_ = 0;

        z_ = 0;

        angle_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sm.mmo.moba.network.protobuf.PositionProtos.internal_static_messages_Position_descriptor;
      }

      @java.lang.Override
      public com.sm.mmo.moba.network.protobuf.PositionProtos.Position getDefaultInstanceForType() {
        return com.sm.mmo.moba.network.protobuf.PositionProtos.Position.getDefaultInstance();
      }

      @java.lang.Override
      public com.sm.mmo.moba.network.protobuf.PositionProtos.Position build() {
        com.sm.mmo.moba.network.protobuf.PositionProtos.Position result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sm.mmo.moba.network.protobuf.PositionProtos.Position buildPartial() {
        com.sm.mmo.moba.network.protobuf.PositionProtos.Position result = new com.sm.mmo.moba.network.protobuf.PositionProtos.Position(this);
        result.x_ = x_;
        result.y_ = y_;
        result.z_ = z_;
        result.angle_ = angle_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sm.mmo.moba.network.protobuf.PositionProtos.Position) {
          return mergeFrom((com.sm.mmo.moba.network.protobuf.PositionProtos.Position)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sm.mmo.moba.network.protobuf.PositionProtos.Position other) {
        if (other == com.sm.mmo.moba.network.protobuf.PositionProtos.Position.getDefaultInstance()) return this;
        if (other.getX() != 0) {
          setX(other.getX());
        }
        if (other.getY() != 0) {
          setY(other.getY());
        }
        if (other.getZ() != 0) {
          setZ(other.getZ());
        }
        if (other.getAngle() != 0) {
          setAngle(other.getAngle());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sm.mmo.moba.network.protobuf.PositionProtos.Position parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sm.mmo.moba.network.protobuf.PositionProtos.Position) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int x_ ;
      /**
       * <code>sint32 x = 3;</code>
       */
      public int getX() {
        return x_;
      }
      /**
       * <code>sint32 x = 3;</code>
       */
      public Builder setX(int value) {
        
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint32 x = 3;</code>
       */
      public Builder clearX() {
        
        x_ = 0;
        onChanged();
        return this;
      }

      private int y_ ;
      /**
       * <code>sint32 y = 4;</code>
       */
      public int getY() {
        return y_;
      }
      /**
       * <code>sint32 y = 4;</code>
       */
      public Builder setY(int value) {
        
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint32 y = 4;</code>
       */
      public Builder clearY() {
        
        y_ = 0;
        onChanged();
        return this;
      }

      private int z_ ;
      /**
       * <code>sint32 z = 5;</code>
       */
      public int getZ() {
        return z_;
      }
      /**
       * <code>sint32 z = 5;</code>
       */
      public Builder setZ(int value) {
        
        z_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint32 z = 5;</code>
       */
      public Builder clearZ() {
        
        z_ = 0;
        onChanged();
        return this;
      }

      private int angle_ ;
      /**
       * <code>int32 angle = 6;</code>
       */
      public int getAngle() {
        return angle_;
      }
      /**
       * <code>int32 angle = 6;</code>
       */
      public Builder setAngle(int value) {
        
        angle_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 angle = 6;</code>
       */
      public Builder clearAngle() {
        
        angle_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:messages.Position)
    }

    // @@protoc_insertion_point(class_scope:messages.Position)
    private static final com.sm.mmo.moba.network.protobuf.PositionProtos.Position DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sm.mmo.moba.network.protobuf.PositionProtos.Position();
    }

    public static com.sm.mmo.moba.network.protobuf.PositionProtos.Position getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Position>
        PARSER = new com.google.protobuf.AbstractParser<Position>() {
      @java.lang.Override
      public Position parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Position(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Position> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Position> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sm.mmo.moba.network.protobuf.PositionProtos.Position getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_Position_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_messages_Position_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017positions.proto\022\010messages\":\n\010Position\022" +
      "\t\n\001x\030\003 \001(\021\022\t\n\001y\030\004 \001(\021\022\t\n\001z\030\005 \001(\021\022\r\n\005angl" +
      "e\030\006 \001(\005B2\n com.sm.mmo.moba.network.proto" +
      "bufB\016PositionProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_messages_Position_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_messages_Position_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_messages_Position_descriptor,
        new java.lang.String[] { "X", "Y", "Z", "Angle", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
